version: '3'
services:
  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - redis-server
  redis-server:
    image: redis
    ports:
      - '6379:6379' # Change the mapping to use a different port
